name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: good
        type: choice
        options:
          - good
          - bad
          - all

env:
  PASSED: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      good: ${{ steps.good.outcome }}
      bad: ${{ steps.bad.outcome }}
      all: ${{ steps.all.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: good
        id: good
        if: "github.event.inputs.deployment_target == 'good'"
        run: pytest -m good --alluredir=allure-results && export PASSED=true
        continue-on-error: true
      - name: bad
        id: bad
        if: "github.event.inputs.deployment_target == 'bad'"
        run: pytest -m bad --alluredir=allure-results && export PASSED=true
        continue-on-error: true
      - name: all
        id: all
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results && export PASSED=true
        continue-on-error: true
      - name: Check result
        if: steps.good.outcome != 'failure' || steps.bad.outcome != 'failure' || steps.all.outcome != 'failure'
        run: |
          echo ${{ steps.good.outcome }}
          echo ${{ steps.bad.outcome }}
          echo ${{ steps.all.outcome }}
          echo "result=passed" >> $GITHUB_ENV
        env:
          PASSED: true
          RESULT: passed
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && sudo tar -zxvf allure-2.23.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
      - run: allure generate -c allure-results -o _site
      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1


  publish-report:
    runs-on: ubuntu-latest
    needs: test
    name: Report publication
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Success
        if: needs.test.outputs.good != 'failure' && needs.test.outputs.bad != 'failure' && needs.test.outputs.all != 'failure'
        run: echo "Test passed"
      - name: Failure
        if: needs.test.outputs.good == 'failure' || needs.test.outputs.bad == 'failure' || needs.test.outputs.all == 'failure'
        run: echo "Test failed"
#        run: echo $PASSED && echo $result && echo $RESULT